### ISSUE TITLE
Why is 'Swin' included in the name of your model?

### ISSUE THREAD

**Issue by Bezdarnost** [JiarunLiu/Swin-UMamba#3]
Thank you very much for your work! 

I am a bit confused and don't understand why you wrote 'Swin' in the name of your model. I haven't found any aspects where it is connected to the original Swin model, or perhaps it is some sort of abbreviation?

**Comment by JiarunLiu** [comment]
Hi @Bezdarnost,

Thanks for your interest. Swin-UMamba is based on the [VMamba](https://github.com/MzeroMiko/VMamba) backbone, sometimes known as the Swin version of Mamba model in vision.

**Comment by XiongZhongxia** [comment]
> Hi @Bezdarnost,
> 
> Thanks for your interest. Swin-UMamba is based on the [VMamba](https://github.com/MzeroMiko/VMamba) backbone, sometimes known as the Swin version of Mamba model in vision.

I think it's really really confusing to the research community, since you actually didn't design an architecture similar to Swin blocks, which calculate attention within windows and shifted windows. 

It‘s very very misleading for researchers like myself, who is searching for a possible solution to adopt MAMBA within window and shifted window.  I thought your work might be exactly the solution I’m looking for, but after a long-time studying of your paper, I realize that you use Swin just to point out the importance of the proposed network. 

What a sad story.

**Comment by Bezdarnost** [comment]
> It‘s very very misleading for researchers like myself, who is searching for a possible solution to adopt MAMBA within window and shifted window. I thought your work might be exactly the solution I’m looking for, but after a long-time studying of your paper, I realize that you use Swin just to point out the importance of the proposed network.

Hi, 

I've implemented Window Mamba for Vision tasks by myself for my experiments. If you want, I can share it with you and we can collaborate. If it will be used in your future paper.
